name: Compile Arduino Firmware

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v2

      - name: Install AVR Board Manager
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:avr

      - name: Compile SPI Slave Sketch
        run: |
          arduino-cli compile --fqbn arduino:avr:pro:cpu=8MHzatmega328 --libraries ./libraries --output-dir build trackpoint-spi-slave/
          rm -f build/*.elf build/*.bin build/*.with_bootloader.*

      - name: Compile I2C Slave Sketch
        run: |
          arduino-cli compile --fqbn arduino:avr:pro:cpu=8MHzatmega328 --libraries ./libraries --output-dir build-i2c trackpoint-i2c-slave/
          rm -f build-i2c/*.elf build-i2c/*.bin build-i2c/*.with_bootloader.*

      - name: Upload SPI Slave Binary
        uses: actions/upload-artifact@v4
        with:
          name: pro-mini-spi-slave
          path: build/

      - name: Upload I2C Slave Binary
        uses: actions/upload-artifact@v4
        with:
          name: pro-mini-i2c-slave
          path: build-i2c/

      - name: Compile Serial Reader Sketch
        run: |
          arduino-cli compile --fqbn arduino:avr:pro:cpu=8MHzatmega328 --libraries ./libraries --output-dir build-serial trackpoint-serial-reader/
          rm -f build-serial/*.elf build-serial/*.bin build-serial/*.with_bootloader.*

      - name: Upload Serial Reader Binary
        uses: actions/upload-artifact@v4
        with:
          name: pro-mini-serial-reader
          path: build-serial/

      - name: Compile Serial Test Sketch
        run: |
          arduino-cli compile --fqbn arduino:avr:pro:cpu=8MHzatmega328 --output-dir build-serial-test serial-test/
          rm -f build-serial-test/*.elf build-serial-test/*.bin build-serial-test/*.with_bootloader.*

      - name: Upload Serial Test Binary
        uses: actions/upload-artifact@v4
        with:
          name: pro-mini-serial-test
          path: build-serial-test/


