name: Compile Arduino Firmware

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v2

      - name: Install AVR Board Manager
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:avr

      - name: Compile SPI Slave Sketch
        run: |
          arduino-cli compile --fqbn arduino:avr:pro:cpu=8MHzatmega328 --libraries ./libraries --output-dir build trackpoint-spi-slave/
          rm -f build/*.elf build/*.bin build/*.with_bootloader.*

      - name: Upload SPI Slave Binary
        uses: actions/upload-artifact@v4
        with:
          name: pro-mini-spi-slave
          path: build/


